# Generated by Django 5.2.8 on 2025-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
