# Generated by Django 5.2.8 on 2025-12-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenedurl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
