# Generated by Django 5.2.8 on 2026-01-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_shortenedurl_user_alter_shortenedurl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='last_acess',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
