# Generated by Django 5.2.8 on 2026-01-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_shortenedurl_last_acess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='last_acess',
            new_name='last_access',
        ),
    ]
